### ISSUE TITLE
CommonJS version?

### ISSUE THREAD

**Issue by OnkelTem** [Richienb/vlc#3]
I included it in my project and it can't be built anymore:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /.../node_modules/@richienb/vlc/dist/index.js from /.../src/commands/play.ts not supported.
```

Could you please support commonjs as well?

**Comment by Richienb** [comment]
I don't plan on re-adding commonjs support.

Try importing this ESM module like this:

```js
const {default: createVlc} = await import('@richienb/vlc');
```

**Comment by OnkelTem** [comment]
Cool, I'll try!

**Comment by OnkelTem** [comment]
No, I'm afraid it doesn't work:

```ts
export default async function (file: string) {
  try {
    const { default: createVlc } = await import("@richienb/vlc"); // <--- fails here
    const vlc = await createVlc();
  } catch (e) {
    console.log(e);
  }
}
```

Error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /.../node_modules/@richienb/vlc/dist/index.js from /.../src/commands/play.ts not supported.
Instead change the require of index.js in /.../src/commands/play.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/.../node_modules/ts-node/dist/index.js:842:20)
    at /.../src/commands/play.ts:30:88
    at async default_1 (/.../src/commands/play.ts:30:40)
    at async Object.handler (/.../src/app.ts:92:13) {
  code: 'ERR_REQUIRE_ESM'
}
```

Any ideas?

**Comment by Richienb** [comment]
This might have something to do with your bundler. Check the compiled JavaScript.
